zuul:
  routes:
#    product: /testProduct/**
    testProduct:
      path: /testProduct/**
      serviceId: product
      sensitiveHeaders:  #设置cookie携带
  ignored-patterns:
    - /product/product/list
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000
