env: dev21

server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.192.32:3306/bottle?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: qwe..032596
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 5
      max-active: 10
      query-timeout: 6000
      transaction-query-timeout: 6000
      remove-abandoned-timeout: 180
      filters: stat

      
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000

  rabbitmq:
    host: 120.78.192.32
    port: 5672
    username: admin
    password: Rrbang123&&mq
  zipkin:
    baseUrl: http://120.78.192.32:9411/
    sender:
      type: web
  sleuth:
    sample:
      probability: 1
logging:
  level:
   root: info


girl:
  name: cusnenjun
  age: 28
  nick-name: myname

